### PR TITLE
Update travis with OS X configuration

### PR DESCRIPTION
**Pull request by plaes**
Improve travis script to cover 3 builds:

* Linux with gcc
* Linux with clang
* OS X with clang (targeting OS X version 10.10)

### CODE REVIEW

**Comment by marekr** [comment]
You broke GCC according to travis

**Comment by marekr** [comment]
Hmm it appears to be a flag conflict, you set std=c++11 which is overriding the std=gnu11 I put there originally (and you didn't remove...)

boost is looking to use 128-bit floats but unforunately GCC only supports them in gnu11 mode or with "-fext-numeric-literals" defined.

Supposedly the 128-bit float support is like this:
-std=c++-03   Yes
-std=gnu++-03 Yes
-std=c++-11   No
-std=gnu++-11 Yes

But I have no clue why.

**Comment by plaes** [comment]
Thanks for digging this up.

I added the `-std=c++11` flag due to the clang-3.5.0 failure:
https://travis-ci.org/plaes/kicad-source-mirror/jobs/105945198

**Comment by marekr** [comment]
Probably best to set the -fext-numeric-literals flag for GCC then.

**Comment by plaes** [comment]
I sort of nailed it now.. (though probably with wrongly sized nails and not a proper hammer) ;)

**Comment by marekr** [comment]
Looks ok, thanks.

You'll probably have trouble pushing this into the kicad upstream because they use jenkins with bzr
http://ci.kicad-pcb.org/

The requirements check on the other hand too, kicad upstream does not do C++11 but Chris Pavilina was working on trying it.

**Pull request merged**
